### ISSUE TITLE
Pseudo is lost when game is started

### ISSUE THREAD

**Issue by delphinemillet** [fabienjuif/2-game#6]
To reproduce:
- go online
- create a room
- start a game
- go back to the previous screen (browser'a back button)
![image](https://user-images.githubusercontent.com/6649877/55552688-562c8f00-56de-11e9-8aed-5198fc24734c.png)

**Comment by fabienjuif** [comment]
You'll can't go back on a room which have a started game.
You'll be redirected to the game.
