### ISSUE TITLE
Go back to the game screen from room screen

### ISSUE THREAD

**Issue by delphinemillet** [fabienjuif/2-game#7]
To reproduce:
- go online
- create
- join a room
- start a game
- go back to the room screen (browser's back button)
    - browser's next button goes to the right screen but nothing is displayed
    - "start game" button does nothing

**Comment by fabienjuif** [comment]
When you'll come back on your room (or room lists), if a game is started and you are in it, it will route you on this game. (Auto reconnect you to the game)
