### ISSUE TITLE
Pseudo is lost when leaving a room

### ISSUE THREAD

**Issue by delphinemillet** [fabienjuif/2-game#9]
To reproduce:
- go online
- create a room
- leave the room
- pseudo is not displayed
![image](https://user-images.githubusercontent.com/6649877/55553836-95101400-56e1-11e9-9425-64db3003399e.png)

**Comment by fabienjuif** [comment]
The server try to keep track of each player state and return state to the player for each event that the player send to the server.

So this issue should be fixed with next release
